db.janusgraph {
  storage {
    backend = cql
    hostname = ["cassandra"]
    port = 9042
    cql {
      cluster-name = thehive-cluster
      keyspace = thehive
      local-datacenter = dc1
      read-consistency-level = ONE
      write-consistency-level = ONE
    }
  }
  index.search {
    backend = elasticsearch
    index-name = thehive
    elasticsearch {
      urls = ["http://172.28.0.31:9200"]
      index-name = thehive
      apply-mapping-at-open = true
    }
  }
}

storage {
  provider = localfs
  localfs.location = /opt/thp/thehive/data
}

play.http.secret.key = "lab-only-thehive-secret-2026-public-demo-rotate-for-real-use"
play.http.parser.maxDiskBuffer = 128m
http.port = 9000
