# =============================================================================
#  Splunk Universal Forwarder — inputs.conf
#  Monitors Wazuh alert JSON logs and ships them to Splunk
# =============================================================================

[monitor:///var/ossec/logs/alerts/alerts.json]
disabled  = false
index     = wazuh
sourcetype = wazuh-alerts
# Wazuh writes one JSON object per line
_raw_serial = false

[monitor:///var/ossec/logs/ossec.log]
disabled   = false
index      = wazuh
sourcetype = wazuh-logs
