# =============================================================================
#  Splunk Universal Forwarder — outputs.conf
#  Forwards data to Splunk indexer via TCP 9997
# =============================================================================

[tcpout]
defaultGroup = splunk_forward
forwardedindex.filter.disable = true
compressed = true
index = wazuh

[tcpout:splunk_forward]
server = splunk:9997

# Set connection timeout and retry settings
connectionTTL = 60
sslPassword = $7$
